PKGNAME := cutils
CUTILS_HEADERS := $(PKGINC_H) $(CBASE_HEADERS)
CUTILS_INCLUDES := $(PKGINCDIR) $(CBASE_INCLUDES)

CUTILS_SRC := $(PKGSRCDIR)
CUTILS_H := $(PKGSRC_H)
CUTILS_INTDIR := $(INTSRCDIR)
CUTILS_OBJ := $(PKGSRC_OBJ)
CUTILS_GCDA := $(PKGSRC_GCDA)
CUTILS := $(PKGLIB)

.PHONY: cutils
cutils: $(CUTILS)

$(CUTILS): $(CUTILS_OBJ)
	@mkdir -p $(@D)
	ar rcs $@ $(CUTILS_OBJ)

$(CUTILS_INTDIR)%.o: $(CUTILS_SRC)%.c $(CUTILS_H) $(CUTILS_HEADERS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(CUTILS_SRC) $(CUTILS_INCLUDES)) $(CFLAGS) -o $@ $<

CUTILS_TEST_LIBS := $(CUTILS) $(CTEST) $(CBASE)

CUTILS_TEST_SRC := $(PKGTESTDIR)
CUTILS_TEST_H := $(PKGTEST_H)
CUTILS_TEST_INTDIR := $(INTTESTDIR)
CUTILS_TEST_OBJ := $(PKGTEST_OBJ)
CUTILS_TEST_GCDA := $(PKGTEST_GCDA)
CUTILS_TEST := $(PKGTEST)

.PHONY: cutils_test
cutils_test: $(CUTILS_TEST)
	@rm -rf $(CUTILS_GCDA) $(CUTILS_TEST_GCDA)
	$(CUTILS_TEST)

$(CUTILS_TEST): $(CUTILS_TEST_OBJ) $(CUTILS_TEST_LIBS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) $(LDFLAGS) -o $@ $(CUTILS_TEST_OBJ) -L$(LIBSDIR) $(patsubst %,-l:%,$(notdir $(CUTILS_TEST_LIBS)))

$(CUTILS_TEST_INTDIR)%.o: $(CUTILS_TEST_SRC)%.c $(CUTILS_TEST_H) $(CUTILS_HEADERS) $(CTEST_HEADERS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(CUTILS_TEST_SRC) $(CUTILS_INCLUDES) $(CTEST_INCLUDES)) $(CFLAGS) -o $@ $<
